"""Builds commercial/projects.html — every commercial project on one long page, in the header's order.

The project pages (commercial/<slug>.html) stay the sources: edit them, then run
    python tools/build_projects.py
from the repo root. Each project's content (between the header and its pager) goes into the long page in
order; the black projects sit together in one dark band. The header links point to the projects on the long
page, and the project pages themselves send visitors there (open one with ?src to see it on its own).
"""
import os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
COM = os.path.join(ROOT, 'commercial')
ORDER = ['sacred-hyper-race', 'nina-ricci', 'loewe', 'clara-luciani', 'horosoaps',
         'carolina-sarria', 'hypertrash', 'posters']
DARK = {'carolina-sarria', 'hypertrash', 'posters'}
OUT = os.path.join(COM, 'projects.html')


def read(slug):
    with open(os.path.join(COM, slug + '.html'), encoding='utf-8') as f:
        return f.read()


def content(slug, html):
    """The project's own part of its page: after the header, before the pager."""
    start = html.index('</div></nav>') + len('</div></nav>')
    end = html.index('<nav class="pager">')
    body = html[start:end].strip('\n')
    if slug == 'sacred-hyper-race':
        body = re.sub(r'<style>\n(.*?)</style>', lambda m: '<style>\n' + scope_case(m.group(1)) + '</style>', body, count=1, flags=re.S)
    if slug in ('hypertrash', 'posters'):
        body = body.replace('id="collage"', f'id="collage-{slug}"')
    if slug == 'loewe':   # the sky starts only when it comes near
        body = body.replace('<iframe src="../sky/loewe.html', '<iframe loading="lazy" src="../sky/loewe.html')
    return body


def scope_case(css):
    """Fortnite's own styles: keep them inside its .case block on the shared page."""
    def fix(m):
        indent, sel, rest = m.group(1), m.group(2), m.group(3)
        if sel.lstrip().startswith('@'):
            return m.group(0)
        parts = [p.strip() for p in sel.split(',')]
        parts = [p if p.startswith('.case') else '.case ' + p for p in parts]
        return indent + ', '.join(parts) + ' {' + rest
    return re.sub(r'^([ \t]*)([^{}\n@][^{}\n]*?)\s*\{(.*)$', fix, css, flags=re.M)


def scripts(slug, html):
    """The project's module scripts, adapted to the shared page (one twPage call, unique collage ids, lazy collages)."""
    tail = html[html.index('<footer'):]
    out = []
    for m in re.finditer(r'<script type="module">\n(.*?)</script>', tail, re.S):
        js = m.group(1)
        js = re.sub(r"[ \t]*import \{ twPage \} from '[^']+';\n", '', js)
        js = re.sub(r'[ \t]*twPage\(\);\n', '', js)
        if slug in ('hypertrash', 'posters'):
            js = js.replace("document.getElementById('collage')", f"document.getElementById('collage-{slug}')")
            js = re.sub(r"\]\);\n", "], { lazy: true });\n", js)
        if js.strip():
            out.append(f'<script type="module">\n{js}</script>')
    return out


def nav(html):
    """The header from a project page, its links turned into links to the projects on this page."""
    top = html[html.index('<nav class="topnav">'):html.index('</div></nav>') + len('</div></nav>')]
    for slug in ORDER:
        top = top.replace(f'href="{slug}.html"', f'href="#p-{slug}"').replace(f'href="projects.html#p-{slug}"', f'href="#p-{slug}"')
    top = top.replace(' class="on" aria-current="page"', '').replace('<li class="on">', '<li>')
    return top


def build():
    pages = {s: read(s) for s in ORDER}
    head = pages['sacred-hyper-race'][:pages['sacred-hyper-race'].index('<body')]
    head = re.sub(r'<title>[^<]*</title>', '<title>Projects — Polina Zinziver</title>', head)
    head = re.sub(r'(<meta name="description" content=")[^"]*', r'\1Commercial projects by Polina Zinziver: 3D animation, CGI, art direction, level design', head)
    head = re.sub(r'\n<script>\nif \(!/\[\?&\]src\\b/.*?</script>', '', head, flags=re.S)   # no redirect here
    parts, js, dark_open = [], [], False
    for slug in ORDER:
        if slug in DARK and not dark_open:
            parts.append('<div class="page-dark dark-zone">'); dark_open = True
        parts.append(f'<div class="proj" id="p-{slug}">\n{content(slug, pages[slug])}\n</div>')
        js += scripts(slug, pages[slug])
    if dark_open:
        parts.append('</div>')
    footer = re.search(r'<footer>.*?</footer>', pages['nina-ricci'], re.S).group(0)
    site_js = re.search(r'<script src="\.\./site\.js[^"]*"></script>', pages['nina-ricci']).group(0)
    tw = re.search(r"import \{ twPage \} from '[^']+';", pages['nina-ricci']).group(0)
    page = f'''{head}<body class="long-page">
<!-- Generated by tools/build_projects.py from the project pages — edit those and run the script. -->

{nav(pages['nina-ricci'])}

{chr(10).join(chr(10) + p + chr(10) for p in parts)}
{footer}

{site_js}
<script type="module">
  {tw}
  twPage();
</script>
{chr(10).join(js)}
<script>
  // the header follows the page: the project in view is underlined; the menu closes after a pick
  (function () {{
    var tabs = [].slice.call(document.querySelectorAll('.topnav .tabs > a[href^="#p-"]'));
    var io = new IntersectionObserver(function (en) {{
      en.forEach(function (e) {{
        if (!e.isIntersecting) return;
        tabs.forEach(function (t) {{ t.classList.toggle('on', t.getAttribute('href') === '#' + e.target.id); }});
      }});
    }}, {{ rootMargin: '-45% 0px -50% 0px' }});
    document.querySelectorAll('.proj').forEach(function (p) {{ io.observe(p); }});
    var dd = document.querySelector('.topnav .dd');
    document.querySelectorAll('.topnav .dd-panel a').forEach(function (a) {{
      a.addEventListener('click', function () {{ if (dd) dd.classList.remove('open'); a.blur(); }});
    }});
    // arriving at a project: land on it once the page has laid itself out
    if (location.hash) addEventListener('load', function () {{
      var t = document.getElementById(location.hash.slice(1));
      if (t) t.scrollIntoView({{ behavior: 'instant' }});
    }});
  }})();
</script>
</body>
</html>
'''
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(page)
    print('built', os.path.relpath(OUT, ROOT), len(page), 'bytes,', len(js), 'module scripts')


if __name__ == '__main__':
    build()
